setup: &setup
  adapter: postgresql
  encoding: unicode

development:
  <<: *setup
  database: commits_io_development
  username: postgres
  password:
  pool: 5
  timeout: 5000

production:
  <<: *setup
  database: commitsio_production
  username: commitsio
  password:
  host: 127.0.0.1
  port: 5433
  pool: 5
  timeout: 5000

test:
  <<: *setup
  host: /var/run/postgresql
  database: commits_io_test
  username: postgres
  password:
  pool: 5
  timeout: 5000
